name: config-wcf
filetype: config$
target: line
type: contains
effort: 800
readiness: 900
category: HTTPS
tags:
- value: transport
patterns:
- value: <system.serviceModel>
  advice: WCF is supported with no transport security
- value: basicHttpsBinding
  advice: Disable HTTPS at the container and allow the external load balancer to terminate
    SSL
- value: mode="Transport"
  advice: Transport security at the container is not supported.  Disable transport
    security on the service
