name: dotnet-ISAPI-Filters-config
filetype: config$
target: line
type: contains
advice: Refer to PCF documetation
effort: 1000
readiness: 1000
category: Unsupported IIS modules
patterns:
- value: <isapiFilters
