name: dotnet-AuthMode-config
filetype: config
target: line
type: regex
defaultpattern: \<authentication\s+mode\=\"%s\"
advice: Ensure compatible configuation
effort: 1000
readiness: 1000
category: Unsupported modules
patterns:
- value: windows
- value: Windows
