name: dotnet-WindowsAuth-config
filetype: config$
target: line
type: contains
advice: Ensure compatible configuation
effort: 1000
readiness: 1000
category: Unsupported modules
patterns:
- value: <windowsAuthentication
