name: java-jvm-runtimeConfigProps
filetype: java$
target: line
type: contains
advice: Do not change these properties at runtime in application code
effort: 50
category: config
tags:
- value: config
- value: api
- value: jvm
- value: javax
recipes:
- uri: https://www.ibm.com/support/knowledgecenter/en/SSAW57_9.0.0/com.ibm.websphere.nd.multiplatform.doc/ae/trun_jvm.html
- uri: https://www.ibm.com/support/knowledgecenter/en/SSEQTP_9.0.0/com.ibm.websphere.wlp.doc/ae/twlp_admin_customvars.html
patterns:
- value: javax.xml.soap.SOAPFactory
- value: javax.xml.parsers.DocumentBuilderFactory
- value: javax.xml.parsers.SAXParserFactory
