name: config-dotnet-webConfig
filetype: config$
target: file
type: simple-text
advice: Convert to Spring based application configuration
category: Config
tags:
- value: file
- value: api
recipes:
- uri: https://app-transformation-cookbook-internal.cfapps.io/client/configuration_in_core/
- uri: https://app-transformation-cookbook-internal.cfapps.io/replatforming/dotnet-framework-externalizing-connection-strings/
patterns:
- value: web.config
- value: Web.config
