name: config-securiy
filetype: config$
target: line
type: contains
advice: Use of generated machine keys can cause problems in cloud applications when
  they are scaled.  Consider disabling use of Machine Keys, or explicitly set the
  key in your configuration.
effort: 100
readiness: 100
category: Security
tags:
- value: config
patterns:
- value: validationKey="AutoGenerate"
- value: decryptionKey="AutoGenerate"
