name: dotnet-IIS-Sessions-config
filetype: config$
target: line
type: contains
advice: Configure .Net session management for PCF
effort: 1000
readiness: 1000
category: sessions
recipes:
- uri: http://cloud.rohitkelapure.com/2016/06/replatforming-net-applications-to-cloud.html
patterns:
- value: StateServer
